export const projects = [
  {
    title: 'GPT-CHAT front page',
    description: "challenge project to understand the full extent of pure css, making a single-page application (SPA), responsive in different devices, from desktop to different smartphones, all in spanish",
      image: '/images/frontendPageTest.png',
      tags: [ 'React', 'CSS'],
    source: 'https://davidms5.github.io/GPTCHAT-webpage/',
    //visit: 'https://github.com/davidms5/GPTCHAT-webpage',
    id: 0,
  },
  {
    title: "Strings&Keys E-commerce",
    description: "full E-commerce website. Authentication & registry with with email or with google using Auth0, custom admin panel made from scratch, integration with mercado pago's API for a payment gateway",
    image: "/images/Captura de pantalla 2023-10-28 072708.png",
    tags: ["React", "Express", "NodeJS", "PostgreSQL", ],
    source: "https://stringsandkeys.up.railway.app/",
    //visit: "https://github.com/adrianavinicki/STRINGSANDKEYSFRONT",// https://github.com/adrianavinicki/STRINGSANDKEYSBACK
    id: 1,
  },
  {
    title: 'Dall-e images Blog',
    description: "the project was made using the MERN stack, to connect with the Dall-e API to generate images with AI. making a Blog to show and download the images generated by the people who access to it",
      image: '/images/Dall-e.png',
      tags: [ 'React', 'tailwindCSS, MongoDB, Express, Cloudinary'],
    source: 'https://ai-images-app-blog.vercel.app/',
    //visit: 'https://github.com/davidms5/AI-images-app-blog',
    id: 2,
  },
  
];
 
export const otra_lista  = [
  {
    title: 'password manager',
    description:"An application to store and manage different type of passwords, having them in a unique and secure place.",
    image: '/images/upcoming/passwords.jpg',
    tags: ['React', 'JavaScript'],
    source: 'https://github.com/davidms5/GPTCHAT-webpage',
    visit: 'https://davidms5.github.io/GPTCHAT-webpage/',
    id: 1,
  },
  {
    title: 'fintech SmartPhone app',
    description: "a mobile application for the exchange of currencies, available for android & IOS with Flutter.",
      image: '/images/upcoming/banking-app-interface_23-2148612400.png',
      tags: ['React', 'WebRTC'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  //{
  //  title: 'Unichat',
  //  description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
  //  image: '/images/4.jpg',
  //  tags: ['React', 'ChatEngine', 'Firebase'],
  //  source: 'https://google.com',
  //  visit: 'https://google.com',
  //  id: 3,
  //},
]

export const TimeLineData = [
  { year: 2020, text: 'Started my journey', },
  { year: 2018, text: 'Making my first projects', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Builded my final portfolio', },
];
